"use client"

import type React from "react"

import { useState } from "react"
import { Loader2 } from "lucide-react"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { ScriptModal } from "@/components/script-modal"
import { VideoPreview } from "@/components/video-preview"

export default function BlogSummaryForm() {
  const [blogContent, setBlogContent] = useState("")
  const [customNotes, setCustomNotes] = useState("")
  const [isLoading, setIsLoading] = useState(false)
  const [isModalOpen, setIsModalOpen] = useState(false)
  const [isProcessing, setIsProcessing] = useState(false)
  const [videoReady, setVideoReady] = useState(false)
  const [generatedContent, setGeneratedContent] = useState({
    script: "",
    videoNotes: "",
  })

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsLoading(true)

    try {
      // Make API call to summarize the blog content using GPT-4o
      const response = await fetch('/api/summarize', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          content: blogContent,
          notes: customNotes
        }),
      })

      if (!response.ok) {
        throw new Error('Failed to summarize content')
      }

      const data = await response.json()

      setGeneratedContent({
        script: data.summary,
        videoNotes: "",
      })
      
      setIsLoading(false)
      setIsModalOpen(true)
    } catch (error) {
      console.error('Error summarizing content:', error)
      setIsLoading(false)
      // You may want to add error handling UI here
      alert('Failed to summarize content. Please try again.')
    }
  }

  const handleGenerateVideo = async () => {
    setIsModalOpen(false)
    setIsProcessing(true)

    try {
      // Here you would make an API call to your video generation service
      // using the script generated by GPT-4o
      // For now, we'll simulate the process with a timeout
      
      // Example API call:
      // const response = await fetch('/api/generate-video', {
      //   method: 'POST',
      //   headers: {
      //     'Content-Type': 'application/json',
      //   },
      //   body: JSON.stringify({
      //     script: generatedContent.script,
      //     videoNotes: generatedContent.videoNotes
      //   }),
      // })
      
      // Simulate video processing for now
      await new Promise(resolve => setTimeout(resolve, 3000))
      
      setIsProcessing(false)
      setVideoReady(true)
    } catch (error) {
      console.error('Error generating video:', error)
      setIsProcessing(false)
      alert('Failed to generate video. Please try again.')
    }
  }

  if (isProcessing) {
    return (
      <Card className="w-full">
        <CardHeader>
          <CardTitle>Processing Your Summary</CardTitle>
          <CardDescription>Please wait while we format your summary.</CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col items-center justify-center py-10">
          <Loader2 className="h-16 w-16 animate-spin text-primary" />
          <p className="mt-4 text-center text-muted-foreground">Formatting your summary...</p>
        </CardContent>
      </Card>
    )
  }

  if (videoReady) {
    return <VideoPreview />
  }

  return (
    <>
      <Card className="w-full">
        <CardHeader>
          <CardTitle>Summarize Your Blog</CardTitle>
          <CardDescription>
            Paste your blog content below and add any notes to help generate a better summary
          </CardDescription>
        </CardHeader>
        <form onSubmit={handleSubmit}>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="blog-content">Blog Content</Label>
              <Textarea
                id="blog-content"
                placeholder="Paste your blog post here..."
                className="min-h-[200px]"
                value={blogContent}
                onChange={(e) => setBlogContent(e.target.value)}
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="custom-notes">Notes for Summary Generation</Label>
              <Textarea
                id="custom-notes"
                placeholder="Add any specific instructions to help generate a better summary..."
                value={customNotes}
                onChange={(e) => setCustomNotes(e.target.value)}
              />
            </div>
          </CardContent>
          <CardFooter>
            <Button type="submit" className="w-full" disabled={isLoading}>
              {isLoading ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Generating Summary...
                </>
              ) : (
                "Generate Summary"
              )}
            </Button>
          </CardFooter>
        </form>
      </Card>

      <ScriptModal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        content={generatedContent}
        setContent={setGeneratedContent}
        onGenerate={handleGenerateVideo}
      />
    </>
  )
}
